from enum import Enum

class License(Enum):
    APACHE_LICENSE = "Apache license"
    APACHE_LICENSE_V1 = "Apache license 1.0"
    APACHE_LICENSE_V2 = "Apache license 2.0"
    AZURE_LICENSE = "Azure License"
    BSD_LICENSE = "BSD license"
    BSD_LICENSE_C0 = "BSD 0-clause license"
    BSD_LICENSE_C2 = "BSD 2-clause license"
    BSD_LICENSE_C3 = "BSD 3-clause license"
    BSD_LICENSE_C4 = "BSD 4-clause license"
    CC0_LICENSE = "Creative Commons Zero, CC-0"
    ECLIPSE_PUBLIC_LICENSE_V1 = "Eclipse public license 1.0 (epl-1.0)"
    ECLIPSE_PUBLIC_LICENSE_V2 = "Eclipse public license 2.0 (epl-2.0)"
    GNU_AFFERO = "GNU Affero general public license (apl)"
    GNU_AFFERO_V3 = "GNU Affero general public license v3 (aplv3)"
    GNU_LESSER_PUBLIC_LICENSE = "GNU lesser general public license"
    GNU_LESSER_PUBLIC_LICENSE_V2 = "GNU lesser general public license v2 (lgplv2)"
    GNU_LESSER_PUBLIC_LICENSE_V3 = "GNU lesser general public license v3 (lgplv3)"
    GNU_PUBLIC_LICENSE = "GNU general public license"
    GNU_PUBLIC_LICENSE_V2 = "GNU general public license v2 (gplv2)"
    GNU_PUBLIC_LICENSE_V3 = "GNU general public license v3 (gplv3)"
    HISTORICAL_PERMISSION_NOTICE = "Historical Permission Notice and Disclaimer (HPND)"
    ISCL_LICENSE = "ISC license (iscl)"
    MIT_LICENSE = "MIT license"
    MIT_CMU = "CMU License (MIT-CMU)"
    MIT_ZERO_LICENSE = "MIT No Attribution"
    MOZILLA_PUBLIC_LICENSE = "Mozilla public license (mpl)"
    MOZILLA_PUBLIC_LICENSE_V2 = "Mozilla public license 2.0 (mpl 2.0)"
    PUBLIC_DOMAIN = "Public domain"
    PYTHON_LICENSE = "Python software foundation license"
    REPOZE_LICENSE = "Repoze public license"
    UNLICENSED_LICENSE = "The Unlicense (Unlicense)"
    WTF_YOU_WANT_LICENSE = "DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE"
    ZOPE_PUBLIC_LICENSE = "Zope Public License"
    ZOPE_PUBLIC_LICENSE_V1 = "Zope Public License v1"
    ZOPE_PUBLIC_LICENSE_V2 = "Zope Public License v2"
    OTHER = "other/proprietary license"
    UNKNOWN_LICENSE = "UNKNOWN"

LICENSES_SYNONYMS = {
    License.APACHE_LICENSE_V1.value.lower(): License.APACHE_LICENSE_V1,
    License.APACHE_LICENSE_V2.value.lower(): License.APACHE_LICENSE_V2,
    License.APACHE_LICENSE.value.lower(): License.APACHE_LICENSE,
    License.AZURE_LICENSE.value.lower(): License.AZURE_LICENSE,
    License.BSD_LICENSE_C0.value.lower(): License.BSD_LICENSE_C0,
    License.BSD_LICENSE_C2.value.lower(): License.BSD_LICENSE_C2,
    License.BSD_LICENSE_C3.value.lower(): License.BSD_LICENSE_C3,
    License.BSD_LICENSE_C4.value.lower(): License.BSD_LICENSE_C4,
    License.BSD_LICENSE.value.lower(): License.BSD_LICENSE,
    License.CC0_LICENSE.value.lower(): License.CC0_LICENSE,
    License.ECLIPSE_PUBLIC_LICENSE_V1.value.lower(): License.ECLIPSE_PUBLIC_LICENSE_V1,
    License.ECLIPSE_PUBLIC_LICENSE_V2.value.lower(): License.ECLIPSE_PUBLIC_LICENSE_V2,
    License.GNU_AFFERO_V3.value.lower(): License.GNU_AFFERO_V3,
    License.GNU_AFFERO.value.lower(): License.GNU_AFFERO,
    License.GNU_LESSER_PUBLIC_LICENSE_V2.value.lower(): License.GNU_LESSER_PUBLIC_LICENSE_V2,
    License.GNU_LESSER_PUBLIC_LICENSE_V3.value.lower(): License.GNU_LESSER_PUBLIC_LICENSE_V3,
    License.GNU_LESSER_PUBLIC_LICENSE.value.lower(): License.GNU_LESSER_PUBLIC_LICENSE,
    License.GNU_PUBLIC_LICENSE_V2.value.lower(): License.GNU_PUBLIC_LICENSE_V2,
    License.GNU_PUBLIC_LICENSE_V3.value.lower(): License.GNU_PUBLIC_LICENSE_V3,
    License.GNU_PUBLIC_LICENSE.value.lower(): License.GNU_PUBLIC_LICENSE,
    License.HISTORICAL_PERMISSION_NOTICE.value.lower(): License.HISTORICAL_PERMISSION_NOTICE,
    License.ISCL_LICENSE.value.lower(): License.ISCL_LICENSE,
    License.MIT_LICENSE.value.lower(): License.MIT_LICENSE,
    License.MIT_CMU.value.lower(): License.MIT_CMU,
    License.MIT_ZERO_LICENSE.value.lower(): License.MIT_ZERO_LICENSE,
    License.MOZILLA_PUBLIC_LICENSE_V2.value.lower(): License.MOZILLA_PUBLIC_LICENSE_V2,
    License.MOZILLA_PUBLIC_LICENSE.value.lower(): License.MOZILLA_PUBLIC_LICENSE,
    License.PUBLIC_DOMAIN.value.lower(): License.PUBLIC_DOMAIN,
    License.PYTHON_LICENSE.value.lower(): License.PYTHON_LICENSE,
    License.REPOZE_LICENSE.value.lower(): License.REPOZE_LICENSE,
    License.UNLICENSED_LICENSE.value.lower(): License.UNLICENSED_LICENSE,
    License.WTF_YOU_WANT_LICENSE.value.lower(): License.WTF_YOU_WANT_LICENSE,
    License.ZOPE_PUBLIC_LICENSE_V1.value.lower(): License.ZOPE_PUBLIC_LICENSE_V1,
    License.ZOPE_PUBLIC_LICENSE_V2.value.lower(): License.ZOPE_PUBLIC_LICENSE_V2,
    License.ZOPE_PUBLIC_LICENSE.value.lower(): License.ZOPE_PUBLIC_LICENSE,
    "mit no attribution license": License.MIT_ZERO_LICENSE,
    "mit no attribution license (mit-0)": License.MIT_ZERO_LICENSE,
    "mit-0": License.MIT_ZERO_LICENSE,
    "mit 0": License.MIT_ZERO_LICENSE,
    "cmu license": License.MIT_CMU,
    "mit-cmu": License.MIT_CMU,
    "cmu-license": License.MIT_CMU,
    "mit license": License.MIT_LICENSE,
    "the mit license": License.MIT_LICENSE,
    "mit license ": License.MIT_LICENSE,
    "mit -  see license.txt.value": License.MIT_LICENSE,
    "mit license (mit)": License.MIT_LICENSE,
    "mit": License.MIT_LICENSE,
    "mit licensed, as found in the license file": License.MIT_LICENSE,
    "the mit license: http://www.opensource.org/licenses/mit-license.php.value": License.MIT_LICENSE,
    "http://www.opensource.org/licenses/mit-license.php.value": License.MIT_LICENSE,
    "the mit license (mit)": License.MIT_LICENSE,
    "mit licence": License.MIT_LICENSE,
    "cc0": License.CC0_LICENSE,
    "cc0 (copyright waived)": License.CC0_LICENSE,
    "cc0 1.0 universal (cc0 1.0) public domain dedication": License.CC0_LICENSE,
    "cc0 1.0 universal (cc0 1.0)": License.CC0_LICENSE,
    "cc0 1.0": License.CC0_LICENSE,
    "cc0 1.0 universal": License.CC0_LICENSE,
    "the unlicense (unlicense)": License.UNLICENSED_LICENSE,
    "the unlicense": License.UNLICENSED_LICENSE,
    "unlicense": License.UNLICENSED_LICENSE,
    "unlicensed": License.UNLICENSED_LICENSE,
    "bsd license": License.BSD_LICENSE,
    "3-clause bsd license": License.BSD_LICENSE_C3,
    "new bsd": License.BSD_LICENSE,
    "bsd": License.BSD_LICENSE,
    "bsd 3-clause": License.BSD_LICENSE_C3,
    "bsd-3-clause": License.BSD_LICENSE_C3,
    "3-bsd": License.BSD_LICENSE_C3,
    "bsd 3": License.BSD_LICENSE_C3,
    "bsd (3-clause)": License.BSD_LICENSE_C3,
    "bsd 2-clause (see license file)": License.BSD_LICENSE_C2,
    "bsd 3 clause": License.BSD_LICENSE_C3,
    "apache-2.0 or bsd": License.BSD_LICENSE_C2,
    "3-clause bsd <http://www.opensource.org/licenses/bsd-license.php.value>": License.BSD_LICENSE_C3,
    "bsd 3-clause license": License.BSD_LICENSE_C3,
    "3-clause bsd": License.BSD_LICENSE_C3,
    "bsd (2-clause)": License.BSD_LICENSE_C2,
    "bsd 2-clause": License.BSD_LICENSE_C2,
    "bsd-2-clause": License.BSD_LICENSE_C2,
    "2-clause bsd license": License.BSD_LICENSE_C2,
    "apache software license": License.APACHE_LICENSE,
    "apache license 2.0": License.APACHE_LICENSE_V2,
    "apache 2.0": License.APACHE_LICENSE_V2,
    "apache license version 2.0": License.APACHE_LICENSE_V2,
    "apache-2.0": License.APACHE_LICENSE_V2,
    "apache license, version 2.0": License.APACHE_LICENSE_V2,
    "http://www.apache.org/licenses/license-2.0": License.APACHE_LICENSE_V2,
    "apache2": License.APACHE_LICENSE_V2,
    "apache license, v2.0": License.APACHE_LICENSE_V2,
    "apache license v2.0": License.APACHE_LICENSE_V2,
    "apache software license v2": License.APACHE_LICENSE_V2,
    "apache 2": License.APACHE_LICENSE_V2,
    "apache license 2": License.APACHE_LICENSE_V2,
    "apache software license (apache 2.0)": License.APACHE_LICENSE_V2,
    "apache2.0": License.APACHE_LICENSE_V2,
    "apache license": License.APACHE_LICENSE,
    "apache 2.0.": License.APACHE_LICENSE_V2,
    "apache": License.APACHE_LICENSE,
    "apache v2": License.APACHE_LICENSE_V2,
    "apache 2 license": License.APACHE_LICENSE_V2,
    '"apache 2.0"': License.APACHE_LICENSE_V2,
    "apache 2.0 license": License.APACHE_LICENSE_V2,
    "apache licence 2.0": License.APACHE_LICENSE_V2,
    "apache license (2.0)": License.APACHE_LICENSE_V2,
    "apache license version 2.0, january 2004 http://www.apache.org/licenses/": License.APACHE_LICENSE_V2,
    'apache license version 2.0, january 2004 http://www.apache.org/licenses/  terms and conditions for use, reproduction, and distribution  1. definitions.  "license" shall mean the terms and conditions for use, reproduction, and distribution as defined by sections 1 through 9 of this document.  "licens': License.APACHE_LICENSE_V2,
    "apache software license 2.0": License.APACHE_LICENSE_V2,
    "apache software license v2.0": License.APACHE_LICENSE_V2,
    "apache software license, version 2.0, http://www.apache.org/licenses/license-2.0": License.APACHE_LICENSE_V2,
    "apache-1.0": License.APACHE_LICENSE_V1,
    "apache-2": License.APACHE_LICENSE_V2,
    "apache-2.0 license": License.APACHE_LICENSE_V2,
    "agpl": License.GNU_AFFERO,
    "agpl 3.0": License.GNU_AFFERO_V3,
    "agpl v3": License.GNU_AFFERO_V3,
    "agpl-3.0": License.GNU_AFFERO_V3,
    "agpl-3.0+": License.GNU_AFFERO_V3,
    "agpl-3.0-only": License.GNU_AFFERO_V3,
    "agplv3": License.GNU_AFFERO_V3,
    "agplv3 (see license file)": License.GNU_AFFERO_V3,
    "apgl3": License.GNU_AFFERO_V3,
    "gnu affero general public license version 3, 19 november 2007 copyright (c) 2007 free software foundation, inc. <http://fsf.org/> everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed. preamble the gnu affero general public license is a": License.GNU_AFFERO_V3,
    "gnu agplv3": License.GNU_AFFERO_V3,
    "gnu affero general public license version 3 (agpl-3.0)": License.GNU_AFFERO_V3,
    "gnu affero general public license v3": License.GNU_AFFERO_V3,
    "gnu affero general public license v3.0": License.GNU_AFFERO_V3,
    "gnu affero general public license, version 3": License.GNU_AFFERO_V3,
    "gnu affero gpl 3.0": License.GNU_AFFERO_V3,
    "gnu affero general public license v3 or later (agplv3+)": License.GNU_AFFERO_V3,
    "gnu library or lesser general public license (lgpl)": License.GNU_LESSER_PUBLIC_LICENSE,
    "gnu lesser general public license v2 (lgplv2)": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "gnu lesser general public license v2": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "lgpl-2.1-only": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "gnu lesser general public license v3 (lgplv3)": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnu lesser general public license v3": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "lgpl, see also license.txt.value": License.GNU_LESSER_PUBLIC_LICENSE,
    "lgpl-2.1 license": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "lgpl-3.0": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "https://www.gnu.org/licenses/lgpl.html": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "lgpl-3.0 license": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnu lesser general public license version 3, 29 june 2007  copyright (c) 2007 free software foundation, inc. <https://fsf.org/> everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.   this version of the gnu lesser general public licen": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnu lesser general public license v2 or later (lgplv2+)": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "gnu lesser general public license v3 or later (lgplv3+)": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "lgplv3+": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "lgpl v3": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "GNU lesser general public license (lgpl)": License.GNU_LESSER_PUBLIC_LICENSE,
    "lgpl": License.GNU_LESSER_PUBLIC_LICENSE,
    "lgpl-3.0-or-later": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "lgpl-2.1+": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "lgpl 2.1": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "lgpl3": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "lgplv2+": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "lgplv3": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gpl 2.0/lgpl 2.1": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "lgpl-2.1": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "gnu general public license (gpl)": License.GNU_PUBLIC_LICENSE,
    "gnu general public license v2 (gplv2)": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "gnu general public license v2 or later (gplv2+)": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "gnu general public license v3 or later (gplv3+)": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "https://www.gnu.org/licenses/gpl-3.0.txt": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "['gplv3 or any later version']": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gpl 2": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "gnu general public license v3 (gplv3)": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gpl3": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gpl2": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "gpl v3": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gplv3": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gplv2": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "gpl": License.GNU_PUBLIC_LICENSE,
    "gpl 3.0": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gpl v2": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "gnu-gpl": License.GNU_PUBLIC_LICENSE,
    "gpl-3.0": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnu": License.GNU_PUBLIC_LICENSE,
    "gnu 3.0": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnu general public license": License.GNU_PUBLIC_LICENSE,
    "gnu general public license v3": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnuv3": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnu general public license version 3, 29 june 2007  copyright (c) 2007 free software foundation, inc. <https://fsf.org/> everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.  preamble  the gnu general public license is a free, copylef": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnu general public license version 3, 29 june 2007 copyright (c) 2007 free software foundation, inc. <http://fsf.org/> everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed. preamble the gnu general public license is a free, copyleft li": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnu general public license version 3, 29 june 2007 copyright (c) 2007 free software foundation, inc. <https://fsf.org/> everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed. preamble the gnu general public license is a free, copyleft l": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnu gpl 3.0": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnu gpl v3.0": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnu gpl v2 or later": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "gnu gpl v3": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnu gpl version 3": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnu gplv2": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "gnu gplv3": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnu gplv3 or any higher": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnu general license version 3": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnu general public licence v3.0": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnu general public license v2.0": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "gnu general public license v3 or later": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnu general public license v3.0": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnu general public license version 3 or later (gplv3+)": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnu general public license, version 3": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnu general public license, version 3, 29 june 2007": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gnu-gplv3": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gpl 2.0": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "gpl 3": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gpl license": License.GNU_PUBLIC_LICENSE,
    "gpl version 2": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "gpl version 3": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gpl-2": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "gpl-2.0": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "gpl-2.0+": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "gpl-2.0-or-later or agpl-3.0-or-later or cern-ohl-s-2.0+": License.GNU_PUBLIC_LICENSE,
    "gpl-3": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gpl-3.0 license": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gpl-3.0+": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gpl-3.0-or-later": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gpl-3.0-orlater": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gpl-v3": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gpl3+": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gpl3.0": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gpl>=3": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gplv03": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gplv2+": License.GNU_LESSER_PUBLIC_LICENSE_V2,
    "gplv3 license": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "gplv3+": License.GNU_LESSER_PUBLIC_LICENSE_V3,
    "python software foundation license": License.PYTHON_LICENSE,
    "psf": License.PYTHON_LICENSE,
    "python": License.PYTHON_LICENSE,
    "python style": License.PYTHON_LICENSE,
    "psf license": License.PYTHON_LICENSE,
    "eclipse public license 2.0 (epl-2.0)": License.ECLIPSE_PUBLIC_LICENSE_V2,
    "eclipse public license v2.0": License.ECLIPSE_PUBLIC_LICENSE_V2,
    "eclipse public license v2.0 / eclipse distribution license v1.0": License.ECLIPSE_PUBLIC_LICENSE_V2,
    "eclipse public license 1.0 (epl-1.0)": License.ECLIPSE_PUBLIC_LICENSE_V1,
    'eclipse public license - v 1.0\n\nthe accompanying program is provided under the terms of this eclipse public\nlicense ("agreement"). any use, reproduction or distribution of the program\nconstitutes recipient"s acceptance of this agreement.\n\n1. definitions\n\n"contribution" means:\n\na) in the case of the ': License.ECLIPSE_PUBLIC_LICENSE_V1,
    "licence.txt": License.UNKNOWN_LICENSE,
    "repoze public license": License.REPOZE_LICENSE,
    "bsd-derived (http://www.repoze.org/license.txt.value)": License.REPOZE_LICENSE,
    "mozilla public license 2.0 (mpl 2.0)": License.MOZILLA_PUBLIC_LICENSE_V2,
    "mpl-2.0": License.MOZILLA_PUBLIC_LICENSE_V2,
    "mpl": License.MOZILLA_PUBLIC_LICENSE,
    "mpl2": License.MOZILLA_PUBLIC_LICENSE_V2,
    "mpl 2.0": License.MOZILLA_PUBLIC_LICENSE_V2,
    "mozilla": License.MOZILLA_PUBLIC_LICENSE,
    "mozilla public license 2.0": License.MOZILLA_PUBLIC_LICENSE_V2,
    "mozilla public license version 2.0": License.MOZILLA_PUBLIC_LICENSE_V2,
    "isc license (iscl)": License.ISCL_LICENSE,
    "isc": License.ISCL_LICENSE,
    "iscl": License.ISCL_LICENSE,
    "historical permission notice and disclaimer (hpnd)": License.HISTORICAL_PERMISSION_NOTICE,
    "hpnd": License.HISTORICAL_PERMISSION_NOTICE,
    "historical permission notice and disclaimer": License.HISTORICAL_PERMISSION_NOTICE,
    "zpl": License.ZOPE_PUBLIC_LICENSE,
    "zpl 1": License.ZOPE_PUBLIC_LICENSE_V1,
    "zpl 2": License.ZOPE_PUBLIC_LICENSE_V2,
    "zpl 2.1": License.ZOPE_PUBLIC_LICENSE_V2,
    "https://aka.ms/azureml-sdk-license": License.AZURE_LICENSE,
    "wtfpl": License.WTF_YOU_WANT_LICENSE,
    "other/proprietary license": License.OTHER,
    "proprietary": License.OTHER,
    "proprietary license": License.OTHER,
}
